all:
	gcc fork.c -o fork_test

fork:
	gcc fork.c -o fork.exe
	./fork.exe

hijo:
	gcc hijo.c -o hijo.exe
	./hijo.exe

signal:
	gcc signal.c -o signal.exe
	./signal.exe

erase:
	rm fork.exe
	rm hijo.exe
	rm signal.exe
